export const INCREMENT_REDUCER = "INCREMENT_REDUCER";
export const DECREMENT_REDUCER = "DECREMENT_REDUCER";
export const GET_METHOD = "GET_METHOD";
export const ADD_METHOD = "ADD_METHOD";
export const DELETE_METHOD = "DELETE_METHOD";
export const UPDATE_METHOD = "UPDATE_METHOD";

